name: Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    name: 'Deploy to Staging'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build:staging
      - run: echo "🛫 Deploy to staging server..."

  deploy-production:
    if: github.ref == 'refs/heads/main'
    name: 'Deploy to Production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build:prod
      - run: echo "🚀 Deploy to production server..." 